// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package supersimple

import (
	"time"

	"go.mongodb.org/mongo-driver/bson/primitive"
)

type Author struct {
	ID          primitive.ObjectID `json:"id"`
	First       string             `json:"first"`
	Last        string             `json:"last"`
	DateOfBirth time.Time          `json:"dateOfBirth"`
	DateOfDeath *time.Time         `json:"dateOfDeath"`
	Books       []*Book            `json:"books"`
}

type Book struct {
	ID          primitive.ObjectID `json:"id"`
	Title       string             `json:"title"`
	Genre       string             `json:"genre"`
	Description string             `json:"description"`
	Publisher   string             `json:"publisher"`
	Authors     []*Author          `json:"authors"`
	OutOfPrint  bool               `json:"outOfPrint"`
}

type NewAuthor struct {
	First       string     `json:"first"`
	Last        string     `json:"last"`
	DateOfBirth time.Time  `json:"dateOfBirth"`
	DateOfDeath *time.Time `json:"dateOfDeath"`
}

type NewBook struct {
	Title       string `json:"title"`
	Genre       string `json:"genre"`
	Description string `json:"description"`
	Publisher   string `json:"publisher"`
	OutOfPrint  bool   `json:"outOfPrint"`
}
